/*
 * SPI_CONFIG.h
 *
 *  Created on: Nov 1, 2023
 *      Author: ELAF MOHAMED
 */

#ifndef SPI_CONFIG_H_
#define SPI_CONFIG_H_




/*Set SPI Enable
 * 1. SPI_DISABLE=0
 * 2. SPI_ENABLE=1
 */
#define SPI_ENABLE_MODE						SPI_ENABLE


/*Set SPI Interrupt Enable
 * 1. SPI_INTERRUPT_DISABLE=0
 * 2. SPI_INTERRUPT_ENABLE=1
 */
#define SPI_INTERRUPT_ENABLE_MODE			SPI_INTERRUPT_DISABLE


/*Set Data Order

 * 1. SPI_DATA_LSB=0
 * 2. SPI_DATA_MSP=1
 */
#define SPI_DATA				SPI_DATA_MSP


/*Select Master/Slave
 * 1. SPI_MASTER=0
 * 2. SPI_SLAVE=1
 */
#define SPI_MASTER_SLAVE_SELECT			SPI_MASTER


/*Set Clock Polarity
 * 1. SPI_RISING_LEADING_FALLING_TRAILING=0
 * 2. SPI_FALLING_LEADING_RISING_TRAILING=1
 */
#define SPI_CLOCK_POLARITY				SPI_RISING_LEADING_FALLING_TRAILING


/*Set Clock Phase
 * 1. SPI_SAMPLE_LEADING_SETUP_TRAILING=0
 * 2. SPI_SETUP_LEADING_SAMPLE_TRAILING=1
 */
#define SPI_CLOCK_PHASE					SPI_SAMPLE_LEADING_SETUP_TRAILING


/*Set Clock Rate Divide
 * 1. SPI_FREQ_DIVIDED_BY_2=0
 * 2. SPI_FREQ_DIVIDED_BY_4=1
 * 3. SPI_FREQ_DIVIDED_BY_8=2
 * 4. SPI_FREQ_DIVIDED_BY_16=3
 * 5. SPI_FREQ_DIVIDED_BY_32=4
 * 6. SPI_FREQ_DIVIDED_BY_64=5
 * 7. SPI_FREQ_DIVIDED_BY_128=6
 */
#define SPI_CLOCK_RATE					SPI_FREQ_DIVIDED_BY_16






#endif /* SPI_CONFIG_H_ */
